// Deterministic demo dataset for the AIPlat console.
//
// Every number here is synthetic. Nothing is read from a deployment, an AWS
// account or a real organization — the screenshots in the README are generated
// from this file so they can be regenerated by anyone, and so no customer data
// ever ends up in a published image.
//
// Determinism matters: the PRNG is seeded, so two runs produce byte-identical
// numbers and a screenshot refresh shows a real diff instead of noise.

const SEED = 20260901;

// mulberry32 — small, fast, seeded. Good enough for shaping demo data.
function rng(seed) {
  let a = seed >>> 0;
  return () => {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = a;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

const r2 = (v) => Number(v.toFixed(2));
const r4 = (v) => Number(v.toFixed(4));
const r6 = (v) => Number(v.toFixed(6));

export const ORG_ID = 'acme';
export const ORG_NAME = 'Acme Corp';

// ---------------------------------------------------------------- models
// A realistic routing table: two Bedrock routes that are the SAME model on
// different paths (that is what lights up the identity/arbitrage badges), a
// cheap fast model, and one self-hosted OpenAI-compatible endpoint.
export const ROUTING = {
  'claude-sonnet': {
    provider: 'bedrock',
    provider_model_id: 'us.anthropic.claude-sonnet-5',
    model_id: 'us.anthropic.claude-sonnet-5',
    region: 'us-west-2',
    prompt_cache: true,
    capabilities: { tool_use: true, multimodal: true, context_window_tokens: 200000, tier: 'frontier' },
  },
  'claude-sonnet-byo': {
    provider: 'bedrock',
    provider_model_id: 'us.anthropic.claude-sonnet-5',
    model_id: 'us.anthropic.claude-sonnet-5',
    role_arn: 'arn:aws:iam::111122223333:role/AIPlatGatewayAccess',
    region: 'us-east-1',
    prompt_cache: true,
    capabilities: { tool_use: true, multimodal: true, context_window_tokens: 200000, tier: 'frontier' },
  },
  'nova-lite': {
    provider: 'bedrock',
    provider_model_id: 'us.amazon.nova-lite-v1:0',
    model_id: 'us.amazon.nova-lite-v1:0',
    region: 'us-west-2',
    capabilities: { tool_use: true, multimodal: true, context_window_tokens: 300000, tier: 'fast' },
  },
  'llama-scout': {
    provider: 'bedrock',
    provider_model_id: 'us.meta.llama4-scout-17b-instruct-v1:0',
    model_id: 'us.meta.llama4-scout-17b-instruct-v1:0',
    region: 'us-west-2',
    capabilities: { tool_use: true, multimodal: true, context_window_tokens: 0, tier: 'fast' },
  },
  'mixtral-selfhosted': {
    provider: 'openai_compatible',
    provider_model_id: 'mixtral-8x7b-instruct',
    base_url: 'https://llm.internal.acme.example/v1',
    capabilities: { tool_use: false, multimodal: false, context_window_tokens: 32000, tier: 'balanced' },
  },
};

export const PRICING = {
  'claude-sonnet': { input: 0.003, output: 0.015, source: 'list' },
  'claude-sonnet-byo': { input: 0.0024, output: 0.012, source: 'contract' },
  'nova-lite': { input: 0.00006, output: 0.00024, source: 'list' },
  'llama-scout': { input: 0.00017, output: 0.00066, source: 'list' },
  'mixtral-selfhosted': { input: 0, output: 0 },
};

export const MODEL_ORDER = ['claude-sonnet', 'claude-sonnet-byo', 'nova-lite', 'llama-scout', 'mixtral-selfhosted'];

export const CONFIG = {
  org_name: ORG_NAME,
  billing_email: 'finops@acme.example',
  timezone: 'America/Sao_Paulo',
  currency: 'USD',
  billing_address: '1 Example Street, Suite 100',
  tax_id: '00.000.000/0001-00',
  routing: ROUTING,
  pricing: PRICING,
  model_order: MODEL_ORDER,
  allowed_models: [],
  budget: { limit_usd: 500, action: 'degrade' },
  rate_limits: { requests_per_minute: 600, tokens_per_minute: 200000 },
  guardrails: { mask_pii: true, block_secrets: true, block_injection: true, no_store: false },
  alerts: {
    webhook_url: 'https://hooks.example.com/services/aiplat-finops',
    cost_usd: { on: true, threshold: 250 },
    latency_ms: { on: true, threshold: 3000 },
    cache_below: { on: true, threshold: 20 },
    error_rate: { on: true, threshold: 5 },
    provider_capacity: { on: true, threshold: 1 },
    slo_burn: { on: true, threshold: 1 },
    anomaly: { on: true, threshold: 1 },
  },
  bundles: {},
};

// ---------------------------------------------------------------- usage
const DAYS = 30;

// One pass builds the whole period so the totals and the series can never
// disagree — a mismatch between a card and its chart is the kind of thing that
// makes a screenshot look broken.
function buildUsage() {
  const rnd = rng(SEED);
  const labels = [];
  const series = [];
  const byReasonSeries = {
    cache: [], provider_prompt_cache: [], provider_arbitrage: [],
    semantic_cache: [], auto_cheapest: [], fallback: [], budget_degrade: [],
  };

  const totals = {
    cost: 0, requests: 0, cacheHits: 0, tokensIn: 0, tokensOut: 0, latencySum: 0,
    saved: { cache: 0, provider_prompt_cache: 0, provider_arbitrage: 0, semantic_cache: 0, auto_cheapest: 0, fallback: 0, budget_degrade: 0 },
  };

  const start = new Date();
  start.setUTCHours(0, 0, 0, 0);
  start.setUTCDate(start.getUTCDate() - (DAYS - 1));

  for (let i = 0; i < DAYS; i++) {
    const day = new Date(start);
    day.setUTCDate(start.getUTCDate() + i);
    labels.push(day.toISOString().slice(0, 10));

    // Weekdays carry more traffic than weekends; a flat line looks fake.
    const dow = day.getUTCDay();
    const weekend = dow === 0 || dow === 6;
    const base = weekend ? 420 : 1350;
    // Gentle growth across the month so the cumulative chart has a shape.
    const growth = 1 + i * 0.02;
    const requests = Math.round(base * growth * (0.85 + rnd() * 0.3));
    const cacheHits = Math.round(requests * (0.24 + rnd() * 0.1));
    const tokensIn = Math.round(requests * (780 + rnd() * 220));
    const tokensOut = Math.round(requests * (190 + rnd() * 90));
    const cost = r6((tokensIn / 1000) * 0.0016 + (tokensOut / 1000) * 0.0072);
    const latency = Math.round(620 + rnd() * 520);

    series.push({ key: labels[i], cost_usd: cost, requests });

    totals.cost = r6(totals.cost + cost);
    totals.requests += requests;
    totals.cacheHits += cacheHits;
    totals.tokensIn += tokensIn;
    totals.tokensOut += tokensOut;
    totals.latencySum += latency * requests;

    // Savings per mechanism. Cache dominates (it is the verified one), the
    // counterfactual mechanisms are deliberately smaller.
    const sv = {
      cache: r6(cost * (0.17 + rnd() * 0.05)),
      provider_prompt_cache: r6(cost * (0.05 + rnd() * 0.03)),
      provider_arbitrage: r6(cost * (0.04 + rnd() * 0.02)),
      semantic_cache: r6(cost * (0.03 + rnd() * 0.02)),
      auto_cheapest: r6(cost * (0.08 + rnd() * 0.04)),
      fallback: r6(cost * (0.01 + rnd() * 0.01)),
      budget_degrade: r6(i > 22 ? cost * (0.02 + rnd() * 0.02) : 0),
    };
    for (const k of Object.keys(sv)) {
      byReasonSeries[k].push(sv[k]);
      totals.saved[k] = r6(totals.saved[k] + sv[k]);
    }
  }

  const savedVerified = r4(totals.saved.cache + totals.saved.provider_prompt_cache + totals.saved.provider_arbitrage);
  const savedCounter = r4(totals.saved.semantic_cache + totals.saved.auto_cheapest + totals.saved.fallback + totals.saved.budget_degrade);
  const savedTotal = r4(savedVerified + savedCounter);
  const gross = totals.cost + savedTotal;

  // credit + cash is a partition of cost — the console asserts that visually.
  const credit = r4(totals.cost * 0.38);
  const cash = r4(totals.cost - credit);

  const cost = r4(totals.cost);

  return {
    totals: {
      cost_usd: cost,
      requests: totals.requests,
      cache_hits: totals.cacheHits,
      tokens_in: totals.tokensIn,
      tokens_out: totals.tokensOut,
      avg_latency_ms: Math.round(totals.latencySum / totals.requests),
      saved_usd: savedTotal,
      saved_pct: r2((savedTotal / gross) * 100),
      saved_verified_usd: savedVerified,
      saved_verified_pct: r2((savedVerified / gross) * 100),
      saved_counterfactual_usd: savedCounter,
      credit_usd: credit,
      cash_usd: cash,
      list_price_pct: 71,
      cost_list_price_usd: r4(cost * 0.71),
    },
    sli: {
      eligible: Math.round(totals.requests * 0.97),
      bad: Math.round(totals.requests * 0.0016),
      availability_pct: 99.84,
    },
    series,
    by_model: [
      { key: 'claude-sonnet', cost_usd: r4(cost * 0.46) },
      { key: 'claude-sonnet-byo', cost_usd: r4(cost * 0.27) },
      { key: 'nova-lite', cost_usd: r4(cost * 0.15) },
      { key: 'llama-scout', cost_usd: r4(cost * 0.08) },
      { key: 'mixtral-selfhosted', cost_usd: r4(cost * 0.04) },
    ],
    by_feature: [
      { key: 'support-copilot', cost_usd: r4(cost * 0.34) },
      { key: 'checkout', cost_usd: r4(cost * 0.26) },
      { key: 'search', cost_usd: r4(cost * 0.19) },
      { key: 'summarize', cost_usd: r4(cost * 0.13) },
      { key: 'default', cost_usd: r4(cost * 0.08) },
    ],
    by_team: [
      { key: 'platform', cost_usd: r4(cost * 0.41) },
      { key: 'growth', cost_usd: r4(cost * 0.31) },
      { key: 'support', cost_usd: r4(cost * 0.28) },
    ],
    by_app: [
      { key: 'web', cost_usd: r4(cost * 0.38) },
      { key: 'mobile', cost_usd: r4(cost * 0.24) },
      { key: 'batch-jobs', cost_usd: r4(cost * 0.21) },
      { key: 'internal-tools', cost_usd: r4(cost * 0.17) },
    ],
    by_provider: [
      {
        key: 'bedrock',
        requests: Math.round(totals.requests * 0.93),
        tokens_in: Math.round(totals.tokensIn * 0.93),
        tokens_out: Math.round(totals.tokensOut * 0.93),
        cost_usd: r4(cost * 0.96),
        saved_usd: r4(savedTotal * 0.97),
        cache_hits: Math.round(totals.cacheHits * 0.95),
      },
      {
        key: 'openai_compatible',
        requests: Math.round(totals.requests * 0.07),
        tokens_in: Math.round(totals.tokensIn * 0.07),
        tokens_out: Math.round(totals.tokensOut * 0.07),
        cost_usd: r4(cost * 0.04),
        saved_usd: r4(savedTotal * 0.03),
        cache_hits: Math.round(totals.cacheHits * 0.05),
      },
    ],
    savings_by_reason: [
      { key: 'cache', saved_usd: totals.saved.cache },
      { key: 'provider_prompt_cache', saved_usd: totals.saved.provider_prompt_cache },
      { key: 'provider_arbitrage', saved_usd: totals.saved.provider_arbitrage },
      { key: 'semantic_cache', saved_usd: totals.saved.semantic_cache },
      { key: 'auto_cheapest', saved_usd: totals.saved.auto_cheapest },
      { key: 'fallback', saved_usd: totals.saved.fallback },
      { key: 'budget_degrade', saved_usd: totals.saved.budget_degrade },
    ],
    savings_series: { labels, by_reason: byReasonSeries },
    by_swap_class: [
      { key: 'none', requests: Math.round(totals.requests * 0.78) },
      { key: 'same_model', requests: Math.round(totals.requests * 0.13) },
      { key: 'equivalent', requests: Math.round(totals.requests * 0.07) },
      { key: 'downgrade', requests: Math.round(totals.requests * 0.02) },
    ],
  };
}

export const USAGE = buildUsage();

// ---------------------------------------------------------------- records
const FEATURES = ['support-copilot', 'checkout', 'search', 'summarize', 'default'];
const MODELS = ['claude-sonnet', 'claude-sonnet-byo', 'nova-lite', 'llama-scout', 'mixtral-selfhosted'];

// A realistic log page: mostly served, a healthy slice of cache, a few swaps,
// a couple of provider errors and two guardrail blocks. Every branch of the
// Logs renderer is exercised, which is the point of a screenshot.
function buildRecords(n) {
  const rnd = rng(SEED + 7);
  const out = [];
  const now = Date.now();
  for (let i = 0; i < n; i++) {
    // Timestamps walk backwards from now — never into the future.
    const ts = new Date(now - i * 97_000 - Math.floor(rnd() * 40_000)).toISOString().replace(/\.\d+Z$/, 'Z');
    const model = MODELS[Math.floor(rnd() * MODELS.length)];
    const tokensIn = Math.round(500 + rnd() * 1800);
    const tokensOut = Math.round(120 + rnd() * 700);
    const price = PRICING[model] || { input: 0, output: 0 };
    const cost = r6((tokensIn / 1000) * price.input + (tokensOut / 1000) * price.output);
    const rec = {
      ts,
      model,
      requested_model: model,
      provider: ROUTING[model].provider,
      upstream: ROUTING[model].provider === 'bedrock' ? 'bedrock-' + (ROUTING[model].region || 'us-west-2') : 'acme-selfhosted',
      feature: FEATURES[Math.floor(rnd() * FEATURES.length)],
      tokens_in: tokensIn,
      tokens_out: tokensOut,
      cost_usd: cost,
      latency_ms: Math.round(180 + rnd() * 1900),
      result: 'served',
      swap_class: null,
      canary: false,
    };

    const dice = rnd();
    if (dice < 0.26) {
      rec.result = 'cache';
      rec.cost_usd = 0;
      rec.latency_ms = Math.round(18 + rnd() * 60);
    } else if (dice < 0.32) {
      rec.result = 'cache';
      rec.savings_reason = 'semantic_cache';
      rec.cost_usd = 0;
      rec.latency_ms = Math.round(40 + rnd() * 90);
    } else if (dice < 0.40) {
      // Same model reached through the customer's own account: no quality risk.
      rec.requested_model = 'claude-sonnet';
      rec.model = 'claude-sonnet-byo';
      rec.swap_class = 'same_model';
      rec.savings_reason = 'provider_arbitrage';
    } else if (dice < 0.46) {
      rec.requested_model = 'claude-sonnet';
      rec.model = 'nova-lite';
      rec.swap_class = 'equivalent';
      rec.savings_reason = 'auto_cheapest';
    } else if (dice < 0.48) {
      rec.requested_model = 'claude-sonnet';
      rec.model = 'llama-scout';
      rec.swap_class = 'downgrade';
      rec.savings_reason = 'budget_degrade';
    } else if (dice < 0.505) {
      rec.result = 'error';
      rec.reason = rnd() < 0.5 ? 'provider_rate_limited' : 'provider_quota_exceeded';
      rec.detail = 'upstream returned 429 after 2 retries';
      rec.cost_usd = 0;
    } else if (dice < 0.52) {
      rec.result = 'blocked';
      rec.reason = rnd() < 0.5 ? 'secret_detected' : 'prompt_injection';
      rec.detail = 'guardrail matched before the request left the gateway';
      rec.cost_usd = 0;
    } else if (dice < 0.535) {
      rec.canary = true;
      rec.canary_route = 'nova-lite';
    }
    out.push(rec);
  }
  return out;
}

export const RECORDS = buildRecords(200);

// ---------------------------------------------------------------- alerts log
function isoAgo(hours) {
  return new Date(Date.now() - hours * 3600_000).toISOString().replace(/\.\d+Z$/, 'Z');
}

export const ALERT_LOG = [
  { ts: isoAgo(3), rule: 'cost_usd', value: 268.4, threshold: 250, unit: 'US$', delivered: true, status_code: 200, host: 'hooks.example.com', severity: 'warning' },
  { ts: isoAgo(11), rule: 'slo_burn', burn_rate: 14.6, slo_target: 99.9, delivered: true, status_code: 200, host: 'hooks.example.com', severity: 'page' },
  { ts: isoAgo(27), rule: 'error_rate', value: 7.2, threshold: 5, unit: '%', delivered: true, status_code: 200, host: 'hooks.example.com', severity: 'warning' },
  { ts: isoAgo(38), rule: 'anomaly', current_pct: 6.1, baseline_pct: 1.2, delivered: false, status_code: 503, host: 'hooks.example.com', severity: 'ticket' },
  { ts: isoAgo(52), rule: 'provider_capacity', value: 4, threshold: 1, unit: '', delivered: true, status_code: 200, host: 'hooks.example.com', severity: 'page' },
  { ts: isoAgo(96), rule: 'cache_below', value: 17.4, threshold: 20, unit: '%', delivered: true, status_code: 200, host: 'hooks.example.com', severity: 'warning' },
  { ts: isoAgo(140), rule: 'latency_ms', value: 3260, threshold: 3000, unit: 'ms', delivered: true, status_code: 200, host: 'hooks.example.com', severity: 'warning' },
];

// ---------------------------------------------------------------- org tree
export const TEAMS = [
  { id: 'platform', display_name: 'Platform', status: 'active' },
  { id: 'growth', display_name: 'Growth', status: 'active' },
  { id: 'support', display_name: 'Support', status: 'active' },
  { id: 'labs', display_name: 'Labs (2025 pilot)', status: 'archived' },
];

export const APPS = [
  { id: 'web', team: 'platform', display_name: 'Web', status: 'active' },
  { id: 'batch-jobs', team: 'platform', display_name: 'Batch jobs', status: 'active' },
  { id: 'mobile', team: 'growth', display_name: 'Mobile', status: 'active' },
  { id: 'internal-tools', team: 'support', display_name: 'Internal tools', status: 'active' },
];

export const MEMBERS = [
  { email: 'dana@acme.example', role: 'owner', team: 'platform', apps: ['web'], status: 'CONFIRMED', enabled: true },
  { email: 'ravi@acme.example', role: 'admin', team: 'platform', apps: ['web', 'batch-jobs'], status: 'CONFIRMED', enabled: true },
  { email: 'mei@acme.example', role: 'dev', team: 'growth', apps: ['mobile'], status: 'CONFIRMED', enabled: true },
  { email: 'tomas@acme.example', role: 'dev', team: 'support', apps: ['internal-tools'], status: 'FORCE_CHANGE_PASSWORD', enabled: true },
  { email: 'finops@acme.example', role: 'billing', team: 'platform', apps: [], status: 'CONFIRMED', enabled: true },
];

export const KEYS = [
  { id: 'k_01', key_prefix: 'sk-aiplat-w7Qd', team: 'platform', app: 'web', created_at: '2026-06-14T09:12:00Z' },
  { id: 'k_02', key_prefix: 'sk-aiplat-b3Km', team: 'platform', app: 'batch-jobs', created_at: '2026-06-21T14:41:00Z' },
  { id: 'k_03', key_prefix: 'sk-aiplat-Xp9r', team: 'growth', app: 'mobile', created_at: '2026-07-02T11:05:00Z' },
  { id: 'k_04', key_prefix: 'sk-aiplat-t4Nv', team: 'support', app: 'internal-tools', created_at: '2026-07-19T16:28:00Z' },
  { id: 'k_05', key_prefix: 'sk-aiplat-Ls2h', team: 'growth', app: 'mobile', created_at: '2026-08-08T08:53:00Z' },
];

export const CREDITS = [
  { provider: 'bedrock', amount_usd: 5000, consumed_usd: 1842.66, remaining_usd: 3157.34, expires_at: '2026-12-31', expired: false, active: true },
  { provider: 'openai_compatible', amount_usd: 250, consumed_usd: 250, remaining_usd: 0, expires_at: '2026-07-31', expired: true, active: false },
];

// Settings → audit (membership actions, adminApi shape).
export const ADMIN_AUDIT = [
  { ts: isoAgo(6), actor: 'dana@acme.example', actor_role: 'owner', action: 'member_invite', target: 'tomas@acme.example', detail: 'role=dev team=support' },
  { ts: isoAgo(30), actor: 'ravi@acme.example', actor_role: 'admin', action: 'member_update', target: 'mei@acme.example', detail: 'team growth' },
  { ts: isoAgo(74), actor: 'dana@acme.example', actor_role: 'owner', action: 'invite_resend', target: 'tomas@acme.example', detail: '' },
  { ts: isoAgo(122), actor: 'ravi@acme.example', actor_role: 'admin', action: 'password_reset', target: 'mei@acme.example', detail: '' },
];

// Logs → control-plane trail (auditApi shape), with field-level diffs.
export const AUDIT_RECORDS = {
  config: [
    {
      ts: isoAgo(5), action: 'config_update', target: 'budget', scope: 'org/' + ORG_ID,
      actor: { email: 'dana@acme.example', role: 'owner', type: 'user' },
      changes: [
        { path: 'budget.limit_usd', before: 300, after: 500 },
        { path: 'budget.action', before: 'alert', after: 'degrade' },
      ],
      change_count: 2, truncated: false,
    },
    {
      ts: isoAgo(29), action: 'config_update', target: 'guardrails', scope: 'org/' + ORG_ID,
      actor: { email: 'ravi@acme.example', role: 'admin', type: 'user' },
      changes: [{ path: 'guardrails.block_injection', before: false, after: true }],
      change_count: 1, truncated: false,
    },
    {
      ts: isoAgo(53), action: 'config_update', target: 'rate_limits', scope: 'team/growth',
      actor: { email: 'ravi@acme.example', role: 'admin', type: 'user' },
      changes: [{ path: 'rate_limits.requests_per_minute', before: 120, after: 300 }],
      change_count: 1, truncated: false,
    },
    {
      ts: isoAgo(101), action: 'credit_update', target: 'bedrock', scope: 'org/' + ORG_ID,
      actor: { email: 'support@aiplat.example', role: 'platform_admin', type: 'platform_operator' },
      detail: 'balance corrected from the provider invoice',
    },
  ],
  models: [
    {
      ts: isoAgo(9), action: 'model_add', target: 'claude-sonnet-byo', scope: 'org/' + ORG_ID,
      actor: { email: 'ravi@acme.example', role: 'admin', type: 'user' },
      changes: [
        { path: 'routing.claude-sonnet-byo.provider', before: null, after: 'bedrock' },
        { path: 'routing.claude-sonnet-byo.role_arn', before: null, after: 'arn:aws:iam::111122223333:role/AIPlatGatewayAccess' },
      ],
      change_count: 2, truncated: false,
    },
    {
      ts: isoAgo(34), action: 'model_update', target: 'claude-sonnet-byo', scope: 'org/' + ORG_ID,
      actor: { email: 'dana@acme.example', role: 'owner', type: 'user' },
      changes: [
        { path: 'pricing.claude-sonnet-byo.input', before: 0.003, after: 0.0024 },
        { path: 'pricing.claude-sonnet-byo.source', before: 'list', after: 'contract' },
      ],
      change_count: 2, truncated: false,
    },
    {
      ts: isoAgo(88), action: 'provider_secret_set', target: 'openai_compatible', scope: 'org/' + ORG_ID,
      actor: { email: 'ravi@acme.example', role: 'admin', type: 'user' },
      detail: 'credential rotated (value never recorded)',
    },
    {
      ts: isoAgo(160), action: 'model_disable', target: 'mixtral-selfhosted', scope: 'org/' + ORG_ID,
      actor: { email: 'ravi@acme.example', role: 'admin', type: 'user' },
      changes: [{ path: 'allowed_models', before: null, after: ['claude-sonnet', 'nova-lite'] }],
      change_count: 1, truncated: false,
    },
  ],
  members: [
    {
      ts: isoAgo(6), action: 'member_invite', target: 'tomas@acme.example', scope: 'org/' + ORG_ID,
      actor: { email: 'dana@acme.example', role: 'owner', type: 'user' },
      changes: [{ path: 'role', before: null, after: 'dev' }, { path: 'team', before: null, after: 'support' }],
      change_count: 2, truncated: false,
    },
    {
      ts: isoAgo(30), action: 'member_update', target: 'mei@acme.example', scope: 'org/' + ORG_ID,
      actor: { email: 'ravi@acme.example', role: 'admin', type: 'user' },
      changes: [{ path: 'team', before: 'platform', after: 'growth' }],
      change_count: 1, truncated: false,
    },
    {
      ts: isoAgo(210), action: 'team_archive', target: 'labs', scope: 'org/' + ORG_ID,
      actor: { email: 'dana@acme.example', role: 'owner', type: 'user' },
      changes: [{ path: 'status', before: 'active', after: 'archived' }],
      change_count: 1, truncated: false,
    },
    {
      ts: isoAgo(240), action: 'app_create', target: 'batch-jobs', scope: 'team/platform',
      actor: { email: 'ravi@acme.example', role: 'admin', type: 'user' },
      detail: '',
    },
  ],
  keys: [
    {
      ts: isoAgo(21), action: 'key_issue', target: 'sk-aiplat-Ls2h', scope: 'team/growth',
      actor: { email: 'mei@acme.example', role: 'dev', type: 'user' },
      detail: 'app=mobile',
    },
    {
      ts: isoAgo(72), action: 'key_revoke', target: 'sk-aiplat-Qq1z', scope: 'team/growth',
      actor: { email: 'ravi@acme.example', role: 'admin', type: 'user' },
      detail: 'rotated after an offboarding',
    },
    {
      ts: isoAgo(150), action: 'key_issue', target: 'sk-aiplat-t4Nv', scope: 'team/support',
      actor: { email: 'dana@acme.example', role: 'owner', type: 'user' },
      detail: 'app=internal-tools',
    },
  ],
};

// ---------------------------------------------------------------- help + chat
export const FAQ = {
  overview: `# Overview

The Overview answers one question: **is anything wrong right now?**

Each card has its own data source, so one failing source degrades a single card
instead of blanking the page.

- **Reliability** is the SLI over eligible requests. A request the gateway
  rejected for policy reasons is not counted as a platform failure.
- **Cost & Budget** compares the period's spend against the cap you set under
  Limits & Budget.
- **Savings** shows the verified figure, not the optimistic one.

> Clicking any card takes you to the tab that explains it.`,
  roi: `# ROI & Savings

Savings are split into **verified** and **counterfactual**, and the console
never blends them into a single headline number.

- **Verified** — the response was reused (cache) or the same model was served
  from a cheaper path. There is no assumption: the request was not sent, or it
  was sent to the identical model.
- **Counterfactual** — the gateway served a *different* model than the one
  requested. The saving is measured against what the requested model would have
  cost, which assumes that model was the real intent.

> Gain-share conversations should use the verified figure.`,
};

export const CHAT_REPLY = {
  choices: [
    {
      message: {
        role: 'assistant',
        content:
          'A gateway sits between your application and the model providers, so the ' +
          'routing decision, the cost record and the policy check all happen in one ' +
          'place instead of being copy-pasted into every service.\n\n' +
          'Concretely, that buys you three things:\n\n' +
          '1. One base_url. Swapping a provider becomes a config change, not a deploy.\n' +
          '2. One cost ledger. Spend is attributed per team, app and feature before\n' +
          '   the invoice arrives, not reconstructed from it afterwards.\n' +
          '3. One policy point. Budget caps, rate limits and guardrails apply to every\n' +
          '   caller, including the service someone shipped last Friday.',
      },
    },
  ],
  aiplat: {
    model: 'claude-sonnet-byo',
    requested_model: 'claude-sonnet',
    provider: 'bedrock',
    estimated_cost_usd: 0.004128,
    cache_hit: false,
    latency_ms: 1180,
  },
};
