// Local demo server for the AIPlat console.
//
// Serves domains/frontend/site as the document root and answers every API call
// the console makes with the synthetic dataset in fixtures.mjs. No AWS, no
// credentials, no network beyond the Chart.js CDN the page itself loads.
//
//   node demo/server.mjs            # http://127.0.0.1:8787/console.html
//   PORT=9000 node demo/server.mjs
//
// The generated env.js points every API base at "" (same origin), which is why
// there is no CORS handling here: the browser treats the calls as relative.

import { createServer } from 'node:http';
import { readFile } from 'node:fs/promises';
import { extname, join, normalize } from 'node:path';
import { fileURLToPath } from 'node:url';
import * as fx from './fixtures.mjs';

const HERE = fileURLToPath(new URL('.', import.meta.url));
const SITE = join(HERE, '..', 'domains', 'frontend', 'site');
const PORT = Number(process.env.PORT || 8787);

const MIME = {
  '.html': 'text/html; charset=utf-8',
  '.js': 'text/javascript; charset=utf-8',
  '.mjs': 'text/javascript; charset=utf-8',
  '.css': 'text/css; charset=utf-8',
  '.json': 'application/json; charset=utf-8',
  '.svg': 'image/svg+xml',
  '.png': 'image/png',
  '.woff2': 'font/woff2',
  '.ico': 'image/x-icon',
};

// Every base points at this server. It has to be an absolute same-origin URL,
// not "": the console treats a falsy helpApi/auditApi as "this environment has
// no help / no audit domain" and hides those tabs entirely.
const ORIGIN = `http://127.0.0.1:${PORT}`;
const ENV_JS = `// Generated by demo/server.mjs — local demo only, never deployed.
window.AIPLAT = {
  adminApi: "${ORIGIN}",
  gateway: "${ORIGIN}",
  usageApi: "${ORIGIN}",
  keyAdmin: "${ORIGIN}",
  helpApi: "${ORIGIN}",
  auditApi: "${ORIGIN}",
  cognito: { region: "us-west-2", clientId: "demo-client-id", domain: "" },
  social: [],
  platformAccount: "111122223333"
};
`;

function json(res, body, status = 200) {
  const payload = JSON.stringify(body);
  res.writeHead(status, {
    'content-type': 'application/json; charset=utf-8',
    'cache-control': 'no-store',
    'content-length': Buffer.byteLength(payload),
  });
  res.end(payload);
}

// The console asks for arbitrary from/to windows. The demo dataset is a fixed
// 30-day period, so a shorter window is served by slicing the tail rather than
// regenerating — the totals stay internally consistent either way.
function usageSummary(params) {
  const from = params.get('from');
  const to = params.get('to');
  if (!from || !to) return fx.USAGE;
  const days = Math.max(1, Math.round((Date.parse(to) - Date.parse(from)) / 864e5));
  if (days >= fx.USAGE.series.length) return fx.USAGE;

  const series = fx.USAGE.series.slice(-days);
  const labels = fx.USAGE.savings_series.labels.slice(-days);
  const byReason = {};
  for (const [k, v] of Object.entries(fx.USAGE.savings_series.by_reason)) {
    byReason[k] = v.slice(-days);
  }
  // Scale the aggregates by the share of the period that survived the slice, so
  // a 7-day view does not show 30 days of spend.
  const share = series.reduce((s, x) => s + x.cost_usd, 0) /
    fx.USAGE.series.reduce((s, x) => s + x.cost_usd, 0);
  const scale = (n) => Number((n * share).toFixed(6));
  const t = fx.USAGE.totals;

  return {
    ...fx.USAGE,
    totals: {
      ...t,
      cost_usd: scale(t.cost_usd),
      requests: Math.round(t.requests * share),
      cache_hits: Math.round(t.cache_hits * share),
      tokens_in: Math.round(t.tokens_in * share),
      tokens_out: Math.round(t.tokens_out * share),
      saved_usd: scale(t.saved_usd),
      saved_verified_usd: scale(t.saved_verified_usd),
      saved_counterfactual_usd: scale(t.saved_counterfactual_usd),
      credit_usd: scale(t.credit_usd),
      cash_usd: scale(t.cash_usd),
      cost_list_price_usd: scale(t.cost_list_price_usd),
    },
    sli: {
      eligible: Math.round(fx.USAGE.sli.eligible * share),
      bad: Math.round(fx.USAGE.sli.bad * share),
      availability_pct: fx.USAGE.sli.availability_pct,
    },
    series,
    savings_series: { labels, by_reason: byReason },
  };
}

function usageRecords(params) {
  const limit = Number(params.get('limit') || 200);
  const result = params.get('result') || '';
  const model = params.get('model') || '';
  const swap = params.get('swap') || '';
  const from = params.get('from');

  let recs = fx.RECORDS;
  if (from) {
    const cut = Date.parse(from);
    recs = recs.filter((r) => Date.parse(r.ts) >= cut);
  }
  if (result) recs = recs.filter((r) => r.result === result);
  if (model) recs = recs.filter((r) => r.model === model);
  if (swap) recs = recs.filter((r) => r.swap_class === swap);
  return { records: recs.slice(0, limit) };
}

async function serveStatic(res, urlPath) {
  // env.js is synthesized: the tracked file is a Terraform template, and the
  // untracked local one holds real deployment endpoints. Neither belongs here.
  if (urlPath === '/env.js') {
    res.writeHead(200, { 'content-type': MIME['.js'], 'cache-control': 'no-store' });
    res.end(ENV_JS);
    return;
  }
  // normalize + a prefix check keeps ".." out of the served tree.
  const rel = normalize(decodeURIComponent(urlPath)).replace(/^(\.\.[/\\])+/, '');

  // In the deployed bucket console.html, vendor/ and fonts/ all sit at the
  // root, which is why the page references them as siblings. On disk the page
  // lives one level down in site/app/, so try site/app/<path> first and then
  // site/<path>. Getting this wrong is silent and expensive: the browser 404s
  // on Tailwind and every screenshot comes out unstyled.
  for (const root of [join(SITE, 'app'), SITE]) {
    const file = join(root, rel);
    if (!file.startsWith(SITE)) continue;
    try {
      const body = await readFile(file);
      res.writeHead(200, {
        'content-type': MIME[extname(file)] || 'application/octet-stream',
        'cache-control': 'no-store',
      });
      res.end(body);
      return;
    } catch {
      // try the next root
    }
  }
  res.writeHead(404).end('not found');
}

const server = createServer(async (req, res) => {
  const url = new URL(req.url, 'http://127.0.0.1');
  const p = url.pathname;
  const q = url.searchParams;

  if (req.method === 'OPTIONS') {
    res.writeHead(204).end();
    return;
  }

  // ---- governance / admin API
  if (p === '/admin/config') {
    // The console fetches the effective config and the org's own raw config.
    // Both are the same object here; the difference only matters when writing.
    return json(res, { ...fx.CONFIG, _scope: 'org/' + fx.ORG_ID, _effective: q.get('effective') === '1' });
  }
  if (p === '/admin/teams') {
    if (q.get('summary') === '1') {
      return json(res, { teams: fx.TEAMS.map((t) => t.id), apps: fx.APPS.map((a) => a.id) });
    }
    return json(res, { teams: fx.TEAMS, apps: fx.APPS });
  }
  if (p === '/admin/members') return json(res, { team_tier: true, members: fx.MEMBERS });
  if (p === '/admin/credits') return json(res, { credits: fx.CREDITS });
  if (p === '/admin/audit') return json(res, { entries: fx.ADMIN_AUDIT });

  // ---- key admin API
  if (p === '/admin/keys') {
    if (q.get('summary') === '1') {
      return json(res, {
        teams: [...new Set(fx.KEYS.map((k) => k.team))],
        apps: [...new Set(fx.KEYS.map((k) => k.app))],
      });
    }
    return json(res, { keys: fx.KEYS });
  }

  // ---- observability / usage API
  if (p === '/usage/summary') return json(res, usageSummary(q));
  if (p === '/usage/records') return json(res, usageRecords(q));
  if (p === '/usage/alerts') return json(res, { alerts: fx.ALERT_LOG });

  // ---- audit domain
  if (p === '/audit/records') {
    const cat = q.get('category') || 'config';
    return json(res, { records: fx.AUDIT_RECORDS[cat] || [] });
  }

  // ---- help domain
  if (p === '/help/faq') {
    const tab = q.get('tab') || 'overview';
    const body = fx.FAQ[tab];
    return json(res, body ? { body, empty: false } : { body: '', empty: true });
  }
  if (p === '/help/internal') return json(res, { body: '', empty: true }, 403);

  // ---- gateway (playground)
  if (p === '/v1/chat/completions' && req.method === 'POST') {
    // Drain the body so the client is never left waiting on backpressure.
    for await (const _ of req) { /* discard */ }
    return json(res, fx.CHAT_REPLY);
  }

  return serveStatic(res, p === '/' ? '/console.html' : p);
});

server.listen(PORT, '127.0.0.1', () => {
  process.stdout.write(`demo console: http://127.0.0.1:${PORT}/console.html\n`);
});
